/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera_link"
      pixel_format: "mjpeg"
      image_width: 1280
      image_height: 720
      camera_name: "aruco_camera"
      camera_info_url: "config/usb_cam/camera_info.yaml"

      
