/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"
      image_width: 1280
      image_height: 720
      camera_name: "usb_camera"
      camera_info_url: "/usb_cam/config/camera_info.yaml"
